# Generated by Django 4.2.26 on 2025-12-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("key_value", "Key-Value Extraction"),
                    ("table", "Table Extraction"),
                    ("classification", "Document Classification"),
                    ("ocr", "OCR"),
                    ("ner", "Named Entity Recognition"),
                    ("content_creation", "Content Creation"),
                ],
                default="key_value",
                max_length=50,
            ),
        ),
    ]
