# Generated by Django 4.2.26 on 2025-12-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_task_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("key_value", "Key-Value Extraction"),
                    ("table", "Table Extraction"),
                    ("classification", "Document Classification"),
                    ("ocr", "OCR"),
                    ("client", "Client"),
                    ("internal", "Internal"),
                    ("content_creation", "Content Creation"),
                    ("ideas", "Ideas"),
                ],
                default="key_value",
                max_length=50,
            ),
        ),
    ]
