# Generated by Django 4.2.26 on 2026-01-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_project_task_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("client", "Client"),
                    ("internal", "Internal"),
                    ("content_creation", "Content Creation"),
                    ("ideas", "Ideas"),
                ],
                default="client",
                max_length=50,
            ),
        ),
    ]
