# Generated by Django 4.2.26 on 2026-01-12 06:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0004_alter_project_task_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="favorited_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorite_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
