# Generated by Django 4.2.26 on 2026-01-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_alter_projectmembership_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("frontend", "Frontend Developer"),
                    ("backend", "Backend Developer"),
                    ("tester", "Testing Engineer"),
                    ("devops", "DevOps Engineer"),
                    ("social_media", "Social Media"),
                    ("viewer", "Viewer"),
                    ("member", "Member"),
                ],
                default="viewer",
                max_length=20,
            ),
        ),
    ]
