# Generated by Django 4.2.26 on 2026-01-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_testing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apicollection",
            name="project_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="Optional reference to a project (UUID for decoupling)",
                null=True,
            ),
        ),
    ]
