# Generated by Django 4.2.26 on 2026-01-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_passwordresetotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="passwordresetotp",
            name="token",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
