# Generated by Django 4.2.26 on 2025-12-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="object_id",
            field=models.CharField(max_length=255),
        ),
    ]
