# Generated by Django 4.2.26 on 2025-12-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groundtruth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF"),
                    ("image", "Image"),
                    ("json", "JSON"),
                    ("text", "Text"),
                    ("video", "Video"),
                    ("mp4", "MP4"),
                    ("other", "Other"),
                ],
                default="pdf",
                max_length=20,
            ),
        ),
    ]
