# Generated by Django 4.2.26 on 2025-12-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasksite", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="project_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
