# Generated by Django 4.2.26 on 2026-01-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_initial"),
        ("tasksite", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="labels",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="projects.label"
            ),
        ),
    ]
