# Generated by Django 4.2.26 on 2025-12-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasksite", "0002_task_priority_task_project_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("reviewed", "Reviewed"),
                    ("deployed", "Deployed"),
                    ("deferred", "Deferred"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
