# Generated by Django 4.2.26 on 2025-12-15 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_task_type"),
        ("tasksite", "0003_alter_task_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="project_name",
        ),
        migrations.AddField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="projects.project",
            ),
        ),
    ]
