# Generated by Django 4.2.26 on 2026-01-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasksite", "0007_taskcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="duration_time",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
