export { Dashboard } from './Dashboard';
export { Login } from './Login';
export { Projects } from './Projects';
export { ProjectCreate } from './ProjectCreate';
export { DocumentCreate } from './DocumentCreate';
export { DocumentDetail } from './DocumentDetail';
export { UserManagement } from './userManagement/UserManagement'
export { MyTask } from './MyTask/MyTask';
export { CreateTask } from './MyTask/CreateTask'
export { TeamPerformance } from './MyTask/TeamPerformance';
export { TaskDetails } from './TaskType/TaskDetails'
export { ContentCreation } from './TaskType/ContentCreation';
export { Documents } from './Documents';
export { ProjectSettings } from './ProjectSettings';
export { Sidebar } from '../components/layout/Sidebar';
export { Calendar } from './Calendar/Calendar';
export { NotificationsPage } from './NotificationsPage';
export { Profile } from  './Profile'
